/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ambulance.glb --transform --exportdefault -o public/models_build/ambulance.jsx 
Files: public/models/ambulance.glb [233.62KB] > /Users/toy/code/game-station/public/models_build/ambulance-transformed.glb [15.45KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models_build/ambulance-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body.geometry} material={materials.colormap} position={[0, 0.2, -0.025]} />
    </group>
  )
}

useGLTF.preload('/models_build/ambulance-transformed.glb')
