/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/boat-sail-a.glb --transform --exportdefault -o public/models_build/boatsaila.jsx 
Files: public/models/boat-sail-a.glb [35.28KB] > /Users/toy/code/game-station/public/models_build/boat-sail-a-transformed.glb [5.62KB] (84%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models_build/boat-sail-a-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['boat-sail-a_1'].geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/models_build/boat-sail-a-transformed.glb')
