/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/direction.glb --transform --exportdefault -o public/models_build/direction.jsx 
Files: public/models/direction.glb [2.54KB] > /Users/toy/code/game-station/public/models_build/direction-transformed.glb [1.29KB] (49%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models_build/direction-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.marker.geometry} material={materials.white} />
    </group>
  )
}

useGLTF.preload('/models_build/direction-transformed.glb')
