/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/firetruck.glb --transform --exportdefault -o public/models_build/firetruck.jsx 
Files: public/models/firetruck.glb [232.47KB] > /Users/toy/code/game-station/public/models_build/firetruck-transformed.glb [14.99KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models_build/firetruck-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body.geometry} material={materials.colormap} position={[0, 0.2, 0]} />
    </group>
  )
}

useGLTF.preload('/models_build/firetruck-transformed.glb')
