/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/frog.glb --transform --exportdefault -o public/models_build/frog.jsx 
Files: public/models/frog.glb [48.27KB] > /Users/toy/code/game-station/public/models_build/frog-transformed.glb [26.56KB] (45%)
Author: daniil.generalov (https://sketchfab.com/daniil.generalov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-frog-d038abf94c504f3e8cfbf3f41f5575a3
Title: Minecraft Frog
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models_build/frog-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="_30" scale={4.419}>
          <group name="Body_29">
            <group name="bone_28">
              <group name="76a8d5cf-0218-085d-2893-9fd8529d4a48_27">
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.material_0} />
              </group>
            </group>
            <group name="23d951f6-9810-f7ab-8991-636c67db6905_0">
              <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.material_0} />
            </group>
            <group name="81741107-719f-e9b1-5221-6308d0a04270_1">
              <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.material_0} />
            </group>
            <group name="e0492a55-72d5-1ee6-8f03-4d4934d2d3c7_2">
              <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.material_0} />
            </group>
            <group name="e1268d2f-4de2-74bf-aabb-0a20daa91adc_3">
              <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.material_0} />
            </group>
            <group name="Legs_26">
              <group name="Right_14">
                <group name="Back_8">
                  <group name="c06b3619-a31c-69eb-78c5-8793425461a6_4">
                    <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.material_0} />
                  </group>
                  <group name="047b305d-e708-162d-9b57-7659681a9591_5">
                    <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.material_0} />
                  </group>
                  <group name="bff507b3-d499-57ca-8b44-ea1012dcb426_6">
                    <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.material_0} />
                  </group>
                  <group name="1734ebe6-b394-2d6e-005b-12a4c15ed89d_7">
                    <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.material_0} />
                  </group>
                </group>
                <group name="Front_13">
                  <group name="d70b09cf-c770-d04a-f2dc-5c6af44662a0_9">
                    <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.material_0} />
                  </group>
                  <group name="10ad5dfc-e804-a30a-94ee-06fe94ac3c1c_10">
                    <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.material_0} />
                  </group>
                  <group name="6fc92ab2-1f5c-00fa-59ef-c96e74a86fa6_11">
                    <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.material_0} />
                  </group>
                  <group name="15b7f3f5-e318-e5c7-fa6d-ee086c4a8d6a_12">
                    <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.material_0} />
                  </group>
                </group>
              </group>
              <group name="Left_25">
                <group name="Back2_19">
                  <group name="7051d56a-6c9d-c923-efe7-729612c238f5_15">
                    <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.material_0} />
                  </group>
                  <group name="4de79c39-df67-0029-9fd5-fb2392c461fc_16">
                    <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.material_0} />
                  </group>
                  <group name="c4237ab0-f244-6b1d-aee0-2e6f1cb4cf5c_17">
                    <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.material_0} />
                  </group>
                  <group name="f71fa937-c6f0-6ff6-47a8-8d305e8ac5d7_18">
                    <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.material_0} />
                  </group>
                </group>
                <group name="Front2_24" position={[0.18, 0.023, -0.144]}>
                  <group name="cf02a73a-a316-725a-a612-ed89a7db709d_20" position={[-0.148, 0.07, 0.069]}>
                    <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.material_0} />
                  </group>
                  <group name="2fb90af6-c9c3-886e-2a25-cb6d1df66a8e_21" position={[-0.18, -0.023, 0.144]}>
                    <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.material_0} />
                  </group>
                  <group name="88379b1c-5da5-6ddc-0233-d97f26239e59_22" position={[-0.18, -0.023, 0.144]}>
                    <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.material_0} />
                  </group>
                  <group name="7e119c89-4dcb-1091-9824-f10c13f624ab_23" position={[-0.18, -0.023, 0.144]}>
                    <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.material_0} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models_build/frog-transformed.glb')
