/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/garbage-truck.glb --transform --exportdefault -o public/models_build/garbagetruck.jsx 
Files: public/models/garbage-truck.glb [268.24KB] > /Users/toy/code/game-station/public/models_build/garbage-truck-transformed.glb [16.75KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models_build/garbage-truck-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.arm.geometry} material={materials.colormap} position={[0, 0.482, 0.325]} />
    </group>
  )
}

useGLTF.preload('/models_build/garbage-truck-transformed.glb')
