/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/gate.glb --transform --exportdefault -o public/models_build/gate.jsx 
Files: public/models/gate.glb [9.89KB] > /Users/toy/code/game-station/public/models_build/gate-transformed.glb [4.28KB] (57%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models_build/gate-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.gate_1.geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/models_build/gate-transformed.glb')
