/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/gate-finish.glb --transform --exportdefault -o public/models_build/gatefinish.jsx 
Files: public/models/gate-finish.glb [9.14KB] > /Users/toy/code/game-station/public/models_build/gate-finish-transformed.glb [4.36KB] (52%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models_build/models_build/models_build/gate-finish-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['gate-finish_1'].geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/models_build/models_build/models_build/gate-finish-transformed.glb')
