/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/police.glb --transform --exportdefault -o public/models_build/police.jsx 
Files: public/models/police.glb [195.36KB] > /Users/toy/code/game-station/public/models_build/police-transformed.glb [13.61KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models_build/police-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['wheel-front-left'].geometry} material={materials.colormap} position={[0.3, 0.3, 0.81]} />
    </group>
  )
}

useGLTF.preload('/models_build/police-transformed.glb')
