/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/road-straight.glb --transform --exportdefault -o public/models_build/roadstraight.jsx 
Files: public/models/road-straight.glb [5.26KB] > /Users/toy/code/game-station/public/models_build/road-straight-transformed.glb [3.86KB] (27%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models_build/road-straight-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['road-straight_1'].geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/models_build/road-straight-transformed.glb')
