/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/taxi.glb --transform --exportdefault -o public/models_build/taxi.jsx 
Files: public/models/taxi.glb [175.6KB] > /Users/toy/code/game-station/public/models_build/taxi-transformed.glb [12.52KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models_build/taxi-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['wheel-front-right'].geometry} material={materials.colormap} position={[-0.3, 0.3, 0.76]} />
    </group>
  )
}

useGLTF.preload('/models_build/taxi-transformed.glb')
